// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSnapshot(arg1) {
  return window['go']['app']['App']['CreateSnapshot'](arg1);
}

export function ForgotPassword(arg1) {
  return window['go']['app']['App']['ForgotPassword'](arg1);
}

export function GetCurrentUser() {
  return window['go']['app']['App']['GetCurrentUser']();
}

export function GetFeaturedRatings(arg1) {
  return window['go']['app']['App']['GetFeaturedRatings'](arg1);
}

export function GetInstalledPackages() {
  return window['go']['app']['App']['GetInstalledPackages']();
}

export function GetPackageDetail(arg1) {
  return window['go']['app']['App']['GetPackageDetail'](arg1);
}

export function GetSystemInfo() {
  return window['go']['app']['App']['GetSystemInfo']();
}

export function InitOAuth(arg1) {
  return window['go']['app']['App']['InitOAuth'](arg1);
}

export function InstallPackage(arg1) {
  return window['go']['app']['App']['InstallPackage'](arg1);
}

export function LoginUser(arg1, arg2) {
  return window['go']['app']['App']['LoginUser'](arg1, arg2);
}

export function LogoutUser() {
  return window['go']['app']['App']['LogoutUser']();
}

export function RefreshToken() {
  return window['go']['app']['App']['RefreshToken']();
}

export function RegisterUser(arg1, arg2, arg3) {
  return window['go']['app']['App']['RegisterUser'](arg1, arg2, arg3);
}

export function ResetPassword(arg1, arg2, arg3) {
  return window['go']['app']['App']['ResetPassword'](arg1, arg2, arg3);
}

export function SearchPackages(arg1) {
  return window['go']['app']['App']['SearchPackages'](arg1);
}

export function SubmitReview(arg1, arg2, arg3) {
  return window['go']['app']['App']['SubmitReview'](arg1, arg2, arg3);
}

export function UninstallPackage(arg1) {
  return window['go']['app']['App']['UninstallPackage'](arg1);
}

export function VoteReview(arg1, arg2) {
  return window['go']['app']['App']['VoteReview'](arg1, arg2);
}
