// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function CreateSnapshot(arg1:string):Promise<string>;

export function ForgotPassword(arg1:string):Promise<void>;

export function GetCurrentUser():Promise<app.AuthUser>;

export function GetFeaturedRatings(arg1:Array<string>):Promise<Record<string, number>>;

export function GetInstalledPackages():Promise<Array<app.PkgInfo>>;

export function GetPackageDetail(arg1:string):Promise<app.PkgInfo>;

export function GetSystemInfo():Promise<app.SystemInfo>;

export function InitOAuth(arg1:string):Promise<void>;

export function InstallPackage(arg1:string):Promise<void>;

export function LoginUser(arg1:string,arg2:string):Promise<app.AuthUser>;

export function LogoutUser():Promise<void>;

export function RefreshToken():Promise<void>;

export function RegisterUser(arg1:string,arg2:string,arg3:string):Promise<app.AuthUser>;

export function ResetPassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SearchPackages(arg1:string):Promise<Array<app.PkgInfo>>;

export function SubmitReview(arg1:string,arg2:number,arg3:string):Promise<void>;

export function UninstallPackage(arg1:string):Promise<void>;

export function VoteReview(arg1:number,arg2:string):Promise<void>;
